---
# override/additions to docker-compose.yml for production
version: '3.7'
services:
  edu-mm:
    volumes:
      - edu-mm-data:/home/mmuser/riffedu/data
      - edu-mm-logs:/home/mmuser/riffedu/logs
      - edu-mm-config:/home/mmuser/riffedu/config
      - edu-mm-plugins:/home/mmuser/riffedu/plugins
      - edu-mm-client-plugins:/home/mmuser/riffedu/client/plugins

volumes:
  edu-mm-data:
  edu-mm-logs:
  edu-mm-config:
  edu-mm-plugins:
  edu-mm-client-plugins:
