---
# override/additions to docker-compose.yml for development
# This defines dev image names and how to build them
# as well as development port mapping and volume binding
# to local repository working directories
version: '3.7'
services:
  edu-mm:
    image: 'rifflearning/riffmm:dev'
    build:
      context: riffmm
      dockerfile: Dockerfile
      target: dev
      args:
        NODE_VER: 12
        GOLANG_VER: 1.14.4
    environment:
      RIFF_LOGLEVEL: debug
    volumes:
      - ${MM_SERVER_PATH-../mattermost-server}:/home/mmuser/go/src/github.com/mattermost/mattermost-server
      - ${MM_WEBAPP_PATH-../mattermost-webapp}:/home/mmuser/go/src/github.com/mattermost/mattermost-webapp

  edu-riffdata:
    image: 'rifflearning/riffdata:dev'
    build:
      context: ${RIFF_SERVER_PATH-../riff-server}/docker
      dockerfile: Dockerfile-dev
      args:
        NODE_VER: 12
        PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      - ${RIFF_SERVER_PATH-../riff-server}:/app

  # Although the dev edu-web is the same as the production edu-web built w/ the release script
  # we give it a dev image name and tag
  edu-web:
    image: 'rifflearning/edu-web:dev'
    build:
      context:  edu-web
      dockerfile: Dockerfile
      args:
        NGINX_VER: latest

  edu-signalmaster:
    image: 'rifflearning/signalmaster:dev'
    build:
      context: ${SIGNALMASTER_PATH-../signalmaster}/docker
      dockerfile: Dockerfile-dev
    volumes:
        - ${SIGNALMASTER_PATH-../signalmaster}:/app

  edu-riffdata-db:
    ports:
      - '27017:27017'

  edu-mm-db:
    ports:
      - '3306:3306'
