---
# override/additions to docker-compose.yml for production
# - the image names are set for deploying to a registry service running
#   on a local swarm (or tunneled into a swarm manager in the cloud)
# - the defaults in this file should be overridden to more strictly define
#   what is built and deployed, but are reasonable values.
#   - uses prod Dockerfile for riff-server & signalmaster from a ref in the github repo
#     use these env vars to override the git ref (ie use a specific version
#     instead of master):
#     - RIFF_SERVER_REF
#     - SIGNALMASTER_REF
#   - edu-riffdata (riff-server) has all files needed copied to the image
#   - tags edu-mm, edu-riffdata & edu-signalmaster images w/ "latest" by default,
#     use these env vars to override:
#     - EDU_MM_TAG
#     - RIFF_SERVER_TAG
#     - SIGNALMASTER_TAG
version: '3.6'
services:
  edu-mm:
    image: '127.0.0.1:5000/rifflearning/edu-mm:${EDU_MM_TAG-latest}'
    build:
      context: edu-mm
      dockerfile: Dockerfile
      target: prod
    volumes:
      - edu-mm-data:/home/mmuser/riffedu/data
      - edu-mm-logs:/home/mmuser/riffedu/logs
      - edu-mm-config:/home/mmuser/riffedu/config
      - edu-mm-plugins:/home/mmuser/riffedu/plugins
      - edu-mm-client-plugins:/home/mmuser/riffedu/client/plugins

  edu-riffdata:
    image: '127.0.0.1:5000/rifflearning/edu-riffdata:${RIFF_SERVER_TAG-latest}'
    build:
      context: https://github.com/rifflearning/riff-server.git#${RIFF_SERVER_REF-master}
      dockerfile: Dockerfile

  edu-signalmaster:
    image: '127.0.0.1:5000/rifflearning/signalmaster:${SIGNALMASTER_TAG-latest}'
    build:
      context: https://github.com/rifflearning/signalmaster.git#${SIGNALMASTER_REF-master}
      dockerfile: Dockerfile

volumes:
  edu-mm-data:
  edu-mm-logs:
  edu-mm-config:
  edu-mm-plugins:
  edu-mm-client-plugins:
