---
# Base configuration for the services that are required to run the riffedu mattermost app
# - the image names are the production images that will be retrieved from the rifflearning
#   github docker package repository.
# - there are volumes defined in docker-compose.prod.yml that are not defined here because
#   they do not apply to the development services which modify these settings
#   and are defined in docker-compose.dev.yml
# - use these env vars to specify the tags for the production images to be deployed:
#     - RIFFMM_TAG
#     - RIFFDATA_TAG
version: '3.7'
services:
  edu-mm:
    image: 'ghcr.io/rifflearning/edu-docker/riffmm:${RIFFMM_TAG-latest}'
    depends_on:
      - edu-mm-db

  edu-riffdata:
    image: 'ghcr.io/rifflearning/riff-server/riffdata:${RIFFDATA_TAG-latest}'
    hostname: edu-riffdata
    ports:
      - '3000:3000'
    depends_on:
      - edu-riffdata-db

  edu-web:
    image: 'ghcr.io/rifflearning/edu-docker/edu-web:latest'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - edu-mm
      - edu-riffdata

  edu-mpns:
    image: 'mattermost/mattermost-push-proxy:5.23.0'
    ports:
      - '8066:8066'
    logging:
        driver: json-file
        options:
            max-file: 4
            max-size: '5m'
    volumes:
      - edu-mpns-config:/mattermost-push-proxy/config
      - edu-mpns-certs:/mattermost-push-proxy/certs

  edu-riffdata-db:
    image: mongo:${MONGO_VER-latest}
    volumes:
      - edu-riffdata-db-data:/data/db
      - edu-riffdata-db-configdb:/data/configdb

  edu-mm-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mostest
      MYSQL_USER: mmuser
      MYSQL_PASSWORD: mostest
      MYSQL_DATABASE: mattermost_test
    volumes:
      - edu-mm-db-data:/var/lib/mysql

volumes:
  edu-riffdata-db-data:
  edu-riffdata-db-configdb:
  edu-mm-db-data:
  edu-mpns-config:
  edu-mpns-certs:
